sudo: required
services: docker
language: minimal

script:
  - docker login -u $DOCKERUSER -p $DOCKERPASS
  - DOCKER_CONTENT_TRUST=1 docker build -t "bsycorp/cloudflare-worker-local:latest" .
  - docker push bsycorp/cloudflare-worker-local
